### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by prezadito** [thebitbrine/spotify-recorder#1]
Not really an issue; more like a silly question...

How do I actually run this? Is there an executable? Do I run something in the command line? I'm confused. Thanks in advance

**Comment by thebitbrine** [comment]
Go to the [releases page](https://github.com/thebitbrine/spotify-recorder/releases) there's two versions one with the installer (which will create shortcuts and stuff) and one which is portable and leaves nothing behind when you delete its files.
Anyhow i would recommend to use the portable one.
